// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDU4GGIWS4LfmYZH4EEWMA_NVWb7L0-uYM',
    appId: '1:44144750826:android:0f5bba6509ede2c2a8e793',
    messagingSenderId: '44144750826',
    projectId: 'ai-build-e0296',
    storageBucket: 'ai-build-e0296.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBh9YLxaFuF7lOPqQP2OOAp6Q4gWBfdtDU',
    appId: '1:44144750826:ios:9f96e493e2c53e88a8e793',
    messagingSenderId: '44144750826',
    projectId: 'ai-build-e0296',
    storageBucket: 'ai-build-e0296.firebasestorage.app',
    iosBundleId: 'com.example.buildWithAi2025',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6s88oS1cUzzEt4WsBMQ5HPeICjCpwTXw',
    appId: '1:44144750826:web:73ebba5bd0e9e714a8e793',
    messagingSenderId: '44144750826',
    projectId: 'ai-build-e0296',
    authDomain: 'ai-build-e0296.firebaseapp.com',
    storageBucket: 'ai-build-e0296.firebasestorage.app',
    measurementId: 'G-0JZ0DN2P5K',
  );

}