name: Build Flutter APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.0'

      - name: Install Dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Notify backend of success
        if: success()
        run: |
          curl -X POST http://localhost:3000/workflow-status \
          -H "Content-Type: application/json" \
          -d '{ "status": "success", "repo": "${ github.repository }", "sha": "${ github.sha }" }'

      - name: Notify backend of failure
        if: failure()
        run: |
          curl -X POST http://localhost:3000/workflow-status \
          -H "Content-Type: application/json" \
          -d '{ "status": "failure", "repo": "${ github.repository }", "sha": "${ github.sha }" }'